version: '3.7'

services:
  caddy:
    image: ${IMAGE_NAME:-lucaslorentz/caddy-docker-proxy}:${IMAGE_TAG:-alpine}
    environment:
      PORT:
      BACKEND_ADDR:
    networks:
      traefik-net:
    configs:
      - source: caddyfile-config
        target: /Caddyfile
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.http.routers.mulo.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.mulo.tls.certresolver: ${TRAEFIK_CERTRESOLVER:-default}
        traefik.http.routers.mulo.rule: Host(`${TRAEFIK_SUBDOMAIN:-mulo}.${TRAEFIK_DOMAIN}`)
        traefik.http.services.mulo.loadbalancer.server.port: ${PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-8M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true

configs:
  caddyfile-config:
    name: ${CADDYFILE_CONFIG_NAME:-mulo-caddyfile}
    file: ./Caddyfile
