services:
  mulo:
    image: ${IMAGE_NAME:-caddy}:${IMAGE_TAG:-latest}
    environment:
      CADDY_PORT:
      BACKEND_ADDR:
    networks:
      traefik-net:
    configs:
      - source: caddyfile-config
        target: /etc/caddy/Caddyfile
    healthcheck:
      test: wget --spider -q http://localhost:${CADDY_PORT}/health
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-5s}
      retries: ${HEALTHCHECK_RETRIES:-10}
      start_period: ${HEALTHCHECK_START_PERIOD:-30s}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: ${TRAEFIK_ENABLE:-true}
        traefik.http.routers.mulo.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.mulo.rule: Host(`${TRAEFIK_SUBDOMAIN:-mulo}.${TRAEFIK_DOMAIN}`)
        traefik.http.services.mulo.loadbalancer.server.port: ${CADDY_PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

configs:
  caddyfile-config:
    name: ${CADDYFILE_CONFIG_NAME:-mulo-caddyfile}
    file: ./config/Caddyfile
