version: '3.7'

services:
  mulo:
    image: ${IMAGE_NAME:-productionwentdown/caddy}:${IMAGE_TAG:-1.0.3}
    environment:
      PORT:
      BACKEND_ADDR:
    networks:
      traefik-net:
    volumes:
      - work-vol:/etc/.caddy
    configs:
      - source: caddyfile-config
        target: /etc/Caddyfile
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      labels:
        traefik.enable: 'true'
        traefik.http.routers.mulo.entrypoints: ${TRAEFIK_ENTRYPOINT:-https}
        traefik.http.routers.mulo.tls.certresolver: ${TRAEFIK_CERTRESOLVER:-default}
        traefik.http.routers.mulo.rule: Host(`${TRAEFIK_SUBDOMAIN:-mulo}.${TRAEFIK_DOMAIN}`)
        traefik.http.services.mulo.loadbalancer.server.port: ${PORT}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-8M}

networks:
  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true

volumes:
  work-vol:
    name: ${WORK_VOL_NAME:-mulo-work-vol}

configs:
  caddyfile-config:
    name: ${CADDYFILE_CONFIG_NAME:-mulo-caddyfile}
    file: ./config/Caddyfile
